### ISSUE TITLE
prediction_with_generate/prediction_from_generate not available in training_args.py

### ISSUE THREAD

**Issue by AmbiTyga** [duongkstn/transformers#1]
## Environment info

     
- `transformers` version: 3.1.0
- Platform: Colab
- Python version: 3.7
- PyTorch version (GPU?): 10.1
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No idea

## Information

Model I am using (Bert, XLNet ...): BERT and GPT2 with `EncoderDecoderModel`

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Try making a model card for generative models
2. Include the argument `predict_from_generate = True` in `TrainingArguments` module

```
training_args = TrainingArguments(
    output_dir="./ambi",
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    predict_with_generate=True,
    evaluate_during_training=True,
    do_train=True,
    do_eval=True,
    logging_steps=1000,
    save_steps=1000,
    eval_steps=1000,
    overwrite_output_dir=True,
    warmup_steps=2000,
    save_total_limit=10,
    fp16=True,
)
```
## Error
```
TypeError: __init__() got an unexpected keyword argument 'predict_with_generate'
```

**Comment by duongkstn** [comment]
sorry, this repo is just a fork of huggingFace's transformers. The reason I forked is that I want to use my own model (not BERT or GPT2 or anything). This repo is for personal experiment only. So I will not answer any issues. 

Rgds,

**Comment by BinhMinhs10** [comment]
in my opinion, you should care about version transforsmer 

> ## Environment info
> 
>     * `transformers` version: 3.1.0
> 
>     * Platform: Colab
> 
>     * Python version: 3.7
> 
>     * PyTorch version (GPU?): 10.1
> 
>     * Tensorflow version (GPU?):
> 
>     * Using GPU in script?: Yes
> 
>     * Using distributed or parallel set-up in script?: No idea
> 
> 
> ### Who can help
> ## Information
> 
> Model I am using (Bert, XLNet ...): BERT and GPT2 with `EncoderDecoderModel`
> 
> The problem arises when using:
> 
>     * [x]  the official example scripts: (give details below)
> 
>     * [ ]  my own modified scripts: (give details below)
> 
> 
> The tasks I am working on is:
> 
>     * [ ]  an official GLUE/SQUaD task: (give the name)
> 
>     * [x]  my own task or dataset: (give details below)
> 
> 
> ## To reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. Try making a model card for generative models
> 
>     2. Include the argument `predict_from_generate = True` in `TrainingArguments` module
> 
> 
> ```
> training_args = TrainingArguments(
>     output_dir="./ambi",
>     per_device_train_batch_size=batch_size,
>     per_device_eval_batch_size=batch_size,
>     predict_with_generate=True,
>     evaluate_during_training=True,
>     do_train=True,
>     do_eval=True,
>     logging_steps=1000,
>     save_steps=1000,
>     eval_steps=1000,
>     overwrite_output_dir=True,
>     warmup_steps=2000,
>     save_total_limit=10,
>     fp16=True,
> )
> ```
> 
> ## Error
> 
> ```
> TypeError: __init__() got an unexpected keyword argument 'predict_with_generate'
> ```

in my opinion, you should care about version transformers

**Comment by AmbiTyga** [comment]
Oh I am sorry for that, still I gone through every version. None of them had such attributes.
